import json
import os

name_list = os.listdir('new_dataset/cresting1/labels/3D_json')

for i in name_list:
    with open('new_dataset/cresting1/labels/3D_json/'+ i,'r') as f:
        data = json.load(f)
        
        location = data['labelingInfo'][0]['3DBox']['location'][0]
        k = open('new_dataset/cresting1/labels/using_data/' + i[-21:-5] + '.txt','w')
        k.write('3 ')
        k.write(str(float(location['x9'])/1280))
        k.write(' ')
        k.write(str(float(location['y9'])/720))
        k.write(' ')
        k.write(str(float(location['x4'])/1280))
        k.write(' ')
        k.write(str(float(location['y4'])/720))
        k.write(' ')
        k.write(str(float(location['x1'])/1280))
        k.write(' ')
        k.write(str(float(location['y1'])/720))
        k.write(' ')
        k.write(str(float(location['x8'])/1280))
        k.write(' ')
        k.write(str(float(location['y8'])/720))
        k.write(' ')
        k.write(str(float(location['x5'])/1280))
        k.write(' ')
        k.write(str(float(location['y5'])/720))
        k.write(' ')
        k.write(str(float(location['x3'])/1280))
        k.write(' ')
        k.write(str(float(location['y3'])/720))
        k.write(' ')
        k.write(str(float(location['x2'])/1280))
        k.write(' ')
        k.write(str(float(location['y2'])/720))
        k.write(' ')
        k.write(str(float(location['x7'])/1280))
        k.write(' ')
        k.write(str(float(location['y7'])/720))
        k.write(' ')
        k.write(str(float(location['x6'])/1280))
        k.write(' ')
        k.write(str(float(location['y6'])/720))
        k.write(' ')
        k.write(str(float(location['x-range'])/1280))
        k.write(' ')
        k.write(str(float(location['y-range'])/720))
        k.write(' ')
            